import type { Metadata } from 'next';
import { Patrick_Hand } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import { ExitModal } from '@/components/ui/modals/exit-modal';
import { DeleteModal } from '@/components/ui/modals/delete-modal';
import './globals.css';

const font = Patrick_Hand({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'Crisp Lingo',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={font.className}>
					<ExitModal />
					<DeleteModal />
					{children}
				</body>
			</html>
		</ClerkProvider>
	);
}
