import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
//import { YOUR_FONT_NAME } from "next/font/google";
import './globals.css';

//TODO: Change font name
//const font = YOUR_FONT_NAME
const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={font.className}>{children}</body>
		</html>
	);
}
