import type { Metadata } from 'next';
import { Patrick_Hand } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';

import { Header } from '@/components/header';

const font = Patrick_Hand({ subsets: ['latin'], weight: ['400'] });

export const metadata: Metadata = {
	title: 'Crisp Lingo',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<Header />
				<body className={font.className}>{children}</body>
			</html>
		</ClerkProvider>
	);
}
